export enum TaskStatus {
   AWAITING_FIXER = "AWAITING_FIXER",
   PENDING_STOCK = "PENDING_STOCK",
   ASSIGNED = "ASSIGNED",
   IN_PROGRESS = "IN_PROGRESS",
   COMPLETED = "COMPLETED",
   CANCELLED = "CANCELLED",
}
