export enum NotificationType {
   SYS_TEST = "SYS_TEST",
   HD_CREATE_REQUEST = "HD_CREATE_REQUEST",
   HM_APPROVE_REQUEST_FIX = "HM_APPROVE_REQUEST_FIX",
   HM_APPROVE_REQUEST_WARRANTY = "HM_APPROVE_REQUEST_WARRANTY",
   HM_APPROVE_REQUEST_RENEW = "HM_APPROVE_REQUEST_RENEW",
   HM_REJECT_REQUEST = "HM_REJECT_REQUEST",
   HM_ASSIGN_TASK = "HM_ASSIGN_TASK",
   STOCK_ACCEPT_EXPORT_WAREHOUSE = "STOCK_ACCEPT_EXPORT_WAREHOUSE",
   S_COMPLETE_ALL_TASKS = "S_COMPLETE_ALL_TASKS",
}
